### ISSUE TITLE
scroll-to not working on second load of a route in the same session

### ISSUE THREAD

**Issue by chriswhong** [jasonkriss/ember-scroll-to#39]
Hi, thanks for `scroll-to`!  

We are experiencing an issue where `scroll-to` works like a charm, but when we navigate away to another route, and come back to the original route, it doesn't work.  (clicking the scroll-to links does nothing, no errors in console)

Any ideas?

**Comment by chriswhong** [comment]
We were able to do a workaround by extending the addon with a new `scrollVertical()`.

The `scroll-to` package includes a computed property that returns a Jquery selection for the div to be scrolled. I think that this computed property was not being recalculated after the route transition. Although the div and id were the same the original one had been destroyed and a new one is created after the transition.

Leaving this here for posterity, I am curious if this works as expected when transitioning away and coming back to a route for others.  If not, the computed property with the selector is probably to blame.

**Comment by laffinkippah** [comment]
Hi, I was experiencing the same issue and can confirm that your workaround worked for me too. Thank you!

**Comment by Duder-onomy** [comment]
I believe this is no longer an issue in 0.6.5 and was indirectly fixed by #37 
I can reproduce this in 0.6.4 no problem. 
@blimmer Can we score an npm publish? #40

**Comment by andycochran** [comment]
I'm still seeing this issue in 0.6.5. As Chris mentions, the following code in `services/scroller.js` does the trick: 
```js
import Em from 'ember';
import Scroller from 'ember-scroll-to/services/scroller';

const { RSVP } = Em;

export default Scroller.extend({
  scrollVertical (target, opts = {}) {
    return new RSVP.Promise((resolve, reject) => {
      // workaround for issue https://github.com/NYCPlanning/labs-nyc-factfinder/issues/304
      const scrollable = Em.$('#profile-content');
      scrollable.animate(
        {
          scrollTop: (scrollable.scrollTop() - scrollable.offset().top) + this.getVerticalCoord(target, opts.offset),
        },
        opts.duration || this.get('duration'),
        opts.easing || this.get('easing'),
        opts.complete,
      )
        .promise()
        .then(resolve, reject);
    });
  },
});
```
